from app import app, db
from models import Subject

subjects = [
    # GE Subjects
    ("GE 101", "Understanding the Self"),
    ("GE 102", "Reading in Philippines History"),
    ("GE 103", "The Contemporary World"),
    ("GE 104", "Mathematics in Modern World"),
    ("GE 105", "Purposive Communication"),
    ("GE 201", "Art Appreciation"),
    ("GE 202", "Science, Technology and Society"),
    ("GE 203", "Ethics"),
    ("GE 204", "Gender and Society"),
    ("GE 205", "Philippine Popular Culture"),
    ("GE 301", "Phil Development Issues"),
    ("GE 302", "Globalization Issues & Impacts"),
    # CSC Subjects
    ("CSC 101", "Introduction to Computing"),
    ("CSC 102", "Business Application Software"),
    ("CSC 103", "Computer Programming 1"),
    ("CSC 104", "Internet Fundamentals"),
    ("CSC 105", "Computer Programming 2"),
    ("CSC 106", "Data Structures & Algorithms"),
    ("CSC 107", "Information Management"),
    ("CSC 201", "Webpage Design and Concept"),
    ("CSC 202", "Computer Programming 3"),
    ("CSC 203", "Software Operation"),
    ("CSC 204", "Discrete Structure 1"),
    ("CSC 205", "Database System"),
    ("CSC 206", "System Analysis and Design"),
    ("CSC 207", "Algorithms & Complexity"),
    ("CSC 208", "Discrete Structure 2"),
    ("CSC 209", "Web Programming"),
    ("CSC 301", "Automata Theory & Formal Languages"),
    ("CSC 302", "Architecture & Organization"),
    ("CSC 303", "Information Assurance & Security"),
    ("CSC 304", "Application Dev't & Emerging Tech"),
    ("CSC 305", "Computation Science"),
    ("CSC 306", "IT Ethics"),
    ("CSC 307", "Event Driven Programming"),
    ("CSC 308", "Networks Communications"),
    ("CSC 309", "Software Engineering 1"),
    ("CSC 310", "Human Computer Interaction"),
    ("CSC 311", "Operating System"),
    ("CSC 312", "Digital Design"),
    ("CSC 313", "Parallel and Distributed Computing"),
    ("CSC 401", "Programming Languages"),
    ("CSC 402", "Software Engineering 2"),
    ("CSC 403", "Graphics and Visual Computing"),
    ("CSC 404", "Intelligent Systems"),
    ("CSC 405", "Fieldtrip and Business Study"),
    ("CSC 406", "CS Thesis 1"),
    ("CSC 407", "Social Issues & Professional Practice"),
    ("CSC 408", "Career Enhancement Seminar"),
    ("CSC 409", "CS Thesis 2"),
    # ISC Subjects
    ("ISC 101", "Introduction to Computing"),
    ("ISC 102", "Business Application Software"),
    ("ISC 103", "Computer Programming 1"),
    ("ISC 202", "Fundamental of Information System"),
    ("ISC 203", "Software Operation"),
    ("ISC 204", "IT Infrastructure & Network Tech."),
    ("ISC 205", "Database System"),
    ("ISC 301", "Organization & Management Concepts"),
    ("ISC 302", "Enterprise Architecture"),
    ("ISC 303", "IS Project Management 1"),
    ("ISC 304", "Application Dev't & Emerging Tech"),
    ("ISC 305", "Financial Management"),
    ("ISC 306", "Quantitative Methods"),
    ("ISC 307", "IT Ethics"),
    ("ISC 401", "IS Strategy, Management & Acquisition"),
    ("ISC 402", "Evaluation of Business Performance"),
    ("ISC 403", "Enterprise Systems"),
    ("ISC 404", "IS Innovation & New Technologies"),
    ("ISC 405", "Business Intelligence"),
    ("ISC 406", "Capstone Project 2"),
    ("ISC 407", "Career Enhancement Seminar"),
    # ACT Subjects
    ("ACT 101", "Computer Fundamentals"),
    ("ACT 102", "Business Application Software"),
    ("ACT 113", "Internet Fundamentals"),
    ("ACT 114", "Database System"),
    ("ACT 115", "Software Operation"),
    ("ACT 201", "Web Page Design & Concept"),
    ("ACT 202", "Fundamentals of Information System"),
    ("ACT 203", "Computer Programming"),
    ("ACT 204", "I.T. Ethics"),
    ("ACT 207", "Algorithms & Complexity"),
    ("ACT 208", "Discrete Structures"),
    ("ACT 209", "Web Programming"),
    ("ACT 210", "Software Engineering"),
    ("ACT 211", "System Analysis & Design"),
    ("ACT 212", "Discrete Structures"),
    ("ACT 213", "Accounting Fundamentals"),
    ("ACT 214", "Fieldtrip / Business Study"),
    # MATH
    ("MATH 101", "College Algebra"),
    ("MATH 301", "Linear Algebra"),
    ("MATH 11", "Mathematics 11"),
    # PE Subjects
    ("PE 101", "Physical Fitness"),
    ("PE 102", "Rhythmic Activities"),
    ("PE 203", "Individual / Dual Sports"),
    ("PE 204", "Team Sports"),
    ("PE 11", "Physical Education 11"),
    # NSTP
    ("NSTP 1", "Civic Welfare & Training Service 1"),
    ("NSTP 2", "Civic Welfare & Training Service 2"),
    # SHS Subjects
    ("ENG 11", "English 11"),
    ("ENG 11A", "English 11A"),
    ("FIL 11", "Filipino 11"),
    ("SCI 11", "Science 11"),
    ("SOC 11", "Social Studies 11"),
    ("MIL 21", "Media and Information Literacy"),
    ("PHI ART 21", "Philippine Arts"),
    ("PHYSCI 21", "Physical Science"),
    ("PHILO 21", "Philosophy"),
    ("PEH 21", "Physical Education and Health"),
    ("HUMSS 21B", "Humanities and Social Sciences"),
    ("ABM 11", "Accountancy, Business and Management 11"),
    ("ABM 21A", "Accountancy, Business and Management 21A"),
    ("GAS 21A", "General Academic Strand 21A"),
    ("FIL 21", "Filipino 21"),
    ("PR 21", "Public Relations 21"),
    ("SHS 12", "Senior High School 12"),
    ("SHS 11", "Senior High School 11"),
    # Other
    ("SOC 101", "Philippine History and Culture"),
    ("SOC 201", "Psychology"),
    ("SOC 202", "Rizal's Life, Works & Writing"),
    ("SOC 401", "Rizal's Life, Works and Writing"),
    ("ENG 101", "Communication Arts 1"),
    ("ENG 102", "Communication Arts 2"),
    ("ENG 203", "Speech & Oral Communication"),
    ("ENG 204", "Technical Writing"),
    ("FIL 101", "Sining ng Pakikipagtalastasan"),
    ("FIL 102", "Panitikang Pilipino"),
    ("HUM 101", "Humanities 1"),
    ("HUM 201", "Humanities 2"),
    ("PHILO 101", "Philosophy of Man"),
    ("PHILO 202", "Logic"),
    ("PE 1", "Physical Fitness"),
    ("PE 2", "Rhythmic Activities"),
    ("PE 3", "Individual / Dual Sports"),
    ("PE 4", "Team Sports"),
    ("NSTP 1", "Civic Welfare & Training Service 1"),
    ("NSTP 2", "Civic Welfare & Training Service 2"),
    ("PRC", "Practicum"),
    ("ICT 11", "Information and Communications Technology 11"),
    ("CSC/ISC/ACT 101", "Computer Programming 1 / Introduction to Computing"),
    ("CSC/ISC/ACT 102", "Business Application Software"),
    ("CSC/ISC/ACT 103", "Computer Programming / Internet Fundamentals"),
    ("CSC/ISC/ACT 104", "Information Management / Database System"),
    ("CSC/ISC/ACT 105", "Computer Programming 2 / Software Operation"),
    ("CSC/ISC/ACT 106", "Data Structures & Algorithms / IT Infrastructure"),
    ("CSC/ISC/ACT 107", "Information Management"),
    ("CSC/ISC/ACT 201", "Webpage Design and Concept / FIS"),
    ("CSC/ISC/ACT 202", "Computer Programming 3 / IS Project Management"),
    ("CSC/ISC/ACT 203", "Software Operation / IS Project Management"),
    ("CSC/ISC/ACT 204", "Discrete Structure 1 / IT Ethics"),
    ("CSC/ISC/ACT 205", "Database System / Financial Management"),
    ("CSC/ISC/ACT 206", "System Analysis and Design / Quantitative Methods"),
    ("CSC/ISC/ACT 207", "Algorithms & Complexity / IT Ethics"),
    ("CSC/ISC/ACT 209", "Web Programming"),
    ("CSC/SC/ACT 107", "Information Management"),
    ("CSC/SC/ACT 304", "Application Dev't & Emerging Tech"),
    ("HUMSS/GAS 11", "Humanities and Social Sciences / General Academic Strand 11"),
    ("ABM 11/GAS 21B", "Accountancy Business Management / General Academic Strand"),
    ("SC 204", "Database System"),
    ("SC 301", "Information Assurance & Security"),
    ("SC 302", "Architecture & Organization"),
]

with app.app_context():
    added = 0
    skipped = 0
    for code, desc in subjects:
        existing = Subject.query.filter_by(subject_code=code).first()
        if not existing:
            subject = Subject(subject_code=code, subject_description=desc)
            db.session.add(subject)
            added += 1
        else:
            skipped += 1
    db.session.commit()
    print(f'✅ Done! Added: {added} subjects, Skipped: {skipped} duplicates')